layout: sidebar
# style: light
# layout: stacked
style: dark

# github: [metadata]

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  exclude:
    archived: true
    forks: false
    projects:
    repo-name: "go-anywhere"


social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: carolzhaang
  # hackerrank: your_username
  instagram: car.zhang
  # keybase: your_username
  linkedin: carolzhang19
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url//
  # youtube: your_username

# github: [metadata] 

# topics:
#   - name: Python
#     image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/1200px-Python-logo-notext.svg.png

#   - name: Web design
#     image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Responsive_Web_Design_Logo.svg/1024px-Responsive_Web_Design_Logo.svg.png

#   - name: Machine Learning
#     image_url: https://downloads.healthcatalyst.com/wp-content/uploads/2017/04/machine-learning-in-healthcare.jpg
